var httpAddres = "http://localhost:3000/";
var httpAddresExplanation = httpAddres + "Explanation";
var httpAddresEvaluation = httpAddres + "Evaluation";
var httpAddresProjects = httpAddres + "Projects";
var httpAddresProjectsPath = httpAddres + "Projects?path=";
var AddresExplanation = "http://localhost:5000/";
var AddresModels = "http://localhost:4000/model_list";
var AddresExplainerLibraries = "http://localhost:5000/";
var AddresExplainerLibrariesGetIngJason = "http://localhost:5000";
var AddresExplainers = "http://localhost:5000/Explainers";
var AddresQuery = "http://localhost:4000/query";